# Generated by Django 4.0.1 on 2022-01-24 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_product_deliver_points_product_deliver_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deliver_points',
        ),
        migrations.AddField(
            model_name='product',
            name='deliver_points',
            field=models.ManyToManyField(blank=True, to='delivery.DeliveryPoint'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 20, 13, 37, 552992), verbose_name='Delivery Date'),
        ),
    ]
