# Generated by Django 4.0.1 on 2022-01-24 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_product_deliver_points_product_deliver_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deliver_points',
        ),
        migrations.AddField(
            model_name='product',
            name='deliver_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliverypoint'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 21, 54, 52, 599625), verbose_name='Delivery Date'),
        ),
    ]
