# Generated by Django 4.0.1 on 2022-01-24 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_product_deliver_points_product_deliver_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deliver_points',
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 22, 32, 50, 276745), verbose_name='Delivery Date'),
        ),
    ]
