# Generated by Django 4.0.1 on 2022-01-25 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_product_deliver_points_deliverypoint_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attachment',
            field=models.FileField(blank=True, upload_to='media', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 16, 30, 47, 919093), verbose_name='Delivery Date'),
        ),
    ]
