# Generated by Django 4.0.5 on 2022-07-19 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_product_attachment_alter_product_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 13, 31, 42, 719528), verbose_name='Delivery Date'),
        ),
    ]
